name = "LoveIt"
license = "MIT"
licenselink = "https://github.com/dillonzq/LoveIt/blob/master/LICENSE"
description = "A Clean, Elegant but Advanced Hugo Theme for Hugo."

homepage = "https://hugoloveit.com"
demosite = "https://hugoloveit.com"

tags = [
  "blog",
  "clean",
  "responsive",
  "dark",
  "theme"
]
features = [
  "cover-image",
  "favicon",
  "multilingual",
  "pagination",
  "social-menu",
  "syntax-highlighting",
  "SEO Optimized"
]

min_version = "0.128.0"

[author]
  name = "Dillon"
  homepage = "https://dillonzq.com/"

[original]
  name = "Fastbyte01"
  homepage = "https://www.fsb01.com/"
  repo = "https://github.com/Fastbyte01/KeepIt"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true   # 允许属性注入
    [markup.goldmark.renderer]
      unsafe = true      # 允许 HTML 标签
